services:
  funkosapi:
    image: funkosapi
    build:
      context: .
      dockerfile: FunkosAPI/Dockerfile
    ports:
      - "5084:8080"
    depends_on:
      - mongodb
      - redis 
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
  
  mongodb:
    image: mongo:latest
    container_name: mongo_funkos
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mongo_data:
  redis-data: